import express, { Request, Response } from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
app.use(express.json());

const PORT = 3000;

// Initialize GoogleGenAI SDK safely
// We lazy-check the key on invocation, but instantiate now.
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || "",
  httpOptions: {
    headers: {
      "User-Agent": "aistudio-build",
    },
  },
});

// JSON schemas for structured extraction
const testCaseSchema = {
  type: Type.OBJECT,
  properties: {
    id: { type: Type.STRING, description: "Unique identifier, e.g., 'TC-001', 'TC-002'" },
    title: { type: Type.STRING, description: "Clear and descriptive title of the test case, max 120 characters" },
    priority: { 
      type: Type.STRING, 
      enum: ["critical", "high", "medium", "low"],
      description: "Priority level based on potential QA business impact" 
    },
    preconditions: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "Preconditions or initial state required for this test"
    },
    steps: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          action: { type: Type.STRING, description: "Action step describing what the user or system should do" },
          expectedResult: { type: Type.STRING, description: "Detailed expected outcome or verification point" }
        },
        required: ["action", "expectedResult"]
      },
      description: "Step-by-step actions and expected results to perform the test"
    },
    labels: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "Useful category labels, tag, component name or group"
    },
    status: {
      type: Type.STRING,
      enum: ["draft"],
      description: "Must be 'draft' initially when generated by Builder"
    }
  },
  required: ["id", "title", "priority", "preconditions", "steps", "labels", "status"]
};

const builderRound1ResponseSchema = {
  type: Type.ARRAY,
  items: testCaseSchema,
  description: "A suite of drafted test cases representing the requirement"
};

const critiqueSchema = {
  type: Type.OBJECT,
  properties: {
    id: { type: Type.STRING, description: "Unique critique identifier, e.g., 'CRIT-001'" },
    targetTestCaseId: { 
      type: Type.STRING, 
      description: "The id of the test case that is flawed, e.g. 'TC-001'. Use empty string or null if the critique is about a MISSING target test case altogether." 
    },
    severity: { 
      type: Type.STRING, 
      enum: ["major", "minor"], 
      description: "Severity of the issue. Major is for missing/wrong core criteria; Minor is for formatting, low risk scenarios, or minor details." 
    },
    issue: { type: Type.STRING, description: "The specific problem plainly and skeptical stated" },
    suggestedFix: { type: Type.STRING, description: "Exactly what is needed to address or mitigate the issue" }
  },
  required: ["id", "severity", "issue", "suggestedFix"]
};

const skepticResponseSchema = {
  type: Type.ARRAY,
  items: critiqueSchema,
  description: "Critiques or holes spotted in the proposed test suite"
};

const builderResponseSchema = {
  type: Type.OBJECT,
  properties: {
    critiqueId: { type: Type.STRING, description: "Critique ID being solved, e.g., 'CRIT-001'" },
    action: { type: Type.STRING, enum: ["fixed", "rejected"], description: "Whether the builder fixed the test case or rejected the objection" },
    explanation: { type: Type.STRING, description: "Clear explanation or rebuttal referring to specific requirement texts" },
    updatedTestCase: {
      type: Type.OBJECT,
      description: "The updated testcase OR the newly added testcase (if targetTestCaseId was missing/null). Use revised or final status.",
      properties: {
        id: { type: Type.STRING },
        title: { type: Type.STRING },
        priority: { type: Type.STRING, enum: ["critical", "high", "medium", "low"] },
        preconditions: { type: Type.ARRAY, items: { type: Type.STRING } },
        steps: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              action: { type: Type.STRING },
              expectedResult: { type: Type.STRING }
            },
            required: ["action", "expectedResult"]
          }
        },
        labels: { type: Type.ARRAY, items: { type: Type.STRING } },
        status: { type: Type.STRING, enum: ["revised", "final", "draft"] }
      },
      required: ["id", "title", "priority", "preconditions", "steps", "labels", "status"]
    }
  },
  required: ["critiqueId", "action", "explanation"]
};

const builderRound2ResponseSchema = {
  type: Type.ARRAY,
  items: builderResponseSchema,
  description: "The Builder responses for each critique point"
};

// Orchestrated call helper with retry
async function generateStructuredJSON<T>(
  prompt: string,
  systemInstruction: string,
  schema: any,
  retryAttempt = 1
): Promise<T> {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is not configured in the secrets panel or environment.");
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: schema,
        temperature: 0.1, // low temperature for precise JSON tasks
      },
    });

    const text = response.text || "";
    try {
      return JSON.parse(text.trim()) as T;
    } catch (parseErr) {
      console.warn(`JSON parsing fail on attempt ${retryAttempt}. Raw Text:`, text);
      if (retryAttempt < 2) {
        console.log("Retrying JSON generation with correction feedback...");
        const correctivePrompt = `${prompt}\n\n[SYSTEM WARNING: Your previous response was not valid JSON. Ensure that your output is ONLY a syntactically correct JSON object or array conforming exactly to the requested Schema. Do not wrap in markdown fences, do not output any other text.]`;
        return await generateStructuredJSON<T>(correctivePrompt, systemInstruction, schema, retryAttempt + 1);
      }
      throw new Error(`Failed to parse AI response as valid JSON: ${(parseErr as Error).message}`);
    }
  } catch (err) {
    throw new Error(`Gemini API Call failed: ${(err as Error).message}`);
  }
}

// Merge response helper implementing lifecycle states
function mergeResponses(
  draftTestCases: any[],
  critiques: any[],
  responses: any[]
): any[] {
  // Map of finalized test cases. Start with clone of drafts marked as final by default,
  // unless they get revised or status is altered below.
  const mergedMap = new Map<string, any>();
  for (const tc of draftTestCases) {
    mergedMap.set(tc.id, { ...tc, status: "final" });
  }

  // Iterate over builder's responses
  for (const resp of responses) {
    const critique = critiques.find((c) => c.id === resp.critiqueId);
    if (!critique) continue;

    // Critique targets an ID
    const targetId = critique.targetTestCaseId;

    if (resp.action === "fixed" && resp.updatedTestCase) {
      if (targetId && targetId !== "null" && targetId !== "") {
        // Revision of a draft test case
        const updated = { ...resp.updatedTestCase, status: "revised" };
        mergedMap.set(targetId, updated);
      } else {
        // Brand new test case created dynamically to cover a requirements gap!
        const newTestCase = { ...resp.updatedTestCase, status: "revised" };
        // If it doesn't already have a valid unique ID or generated a bad one, make sure it has one
        if (!newTestCase.id) {
          const generatedId = `TC-ADD-${Math.floor(100 + Math.random() * 900)}`;
          newTestCase.id = generatedId;
        }
        mergedMap.set(newTestCase.id, newTestCase);
      }
    } else if (resp.action === "rejected") {
      // Critique was rejected, original stands.
      // If the draft testcase is in the map, preserve but ensure its status is "final"
      if (targetId && mergedMap.has(targetId)) {
        const existing = mergedMap.get(targetId);
        mergedMap.set(targetId, { ...existing, status: "final" });
      }
    }
  }

  return Array.from(mergedMap.values());
}

// Health check endpoint
app.get("/api/health", (req: Request, res: Response) => {
  res.json({ status: "ok", time: new Date().toISOString() });
});

// Real Sync Endpoint to UiPath Test Manager via OAuth Client Credentials
app.post("/api/sync-test-case", async (req: Request, res: Response): Promise<void> => {
  const { testCase } = req.body;

  if (!testCase) {
    res.status(400).json({ error: "TestCase payload is required." });
    return;
  }

  const clientId = process.env.UIPATH_CLIENT_ID;
  const clientSecret = process.env.UIPATH_CLIENT_SECRET;
  const org = process.env.UIPATH_ORG;
  const tenant = process.env.UIPATH_TENANT;
  const projectKey = process.env.UIPATH_PROJECT_KEY;

  if (!clientId || !clientSecret || !org || !tenant || !projectKey) {
    const missingKeys = [];
    if (!clientId) missingKeys.push("UIPATH_CLIENT_ID");
    if (!clientSecret) missingKeys.push("UIPATH_CLIENT_SECRET");
    if (!org) missingKeys.push("UIPATH_ORG");
    if (!tenant) missingKeys.push("UIPATH_TENANT");
    if (!projectKey) missingKeys.push("UIPATH_PROJECT_KEY");

    res.status(400).json({
      error: `Missing UiPath configuration: [${missingKeys.join(", ")}]. Please define these keys in the Secrets panel or .env.`,
      configTip: "To complete setup, open settings and define your UiPath External Application credential pair (scopes: 'OR.TestManager' or similar).",
      simulatedFallback: true
    });
    return;
  }

  try {
    console.log("Authenticating with UiPath Identity Service...");
    const tokenUrl = "https://cloud.uipath.com/identity_/connect/token";
    const params = new URLSearchParams();
    params.append("grant_type", "client_credentials");
    params.append("client_id", clientId);
    params.append("client_secret", clientSecret);
    params.append("scope", "OR.TestManager");

    const tokenResponse = await fetch(tokenUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: params.toString(),
    });

    if (!tokenResponse.ok) {
      const tokenErrText = await tokenResponse.text();
      throw new Error(`UiPath OAuth Auth Failed: ${tokenResponse.status} - ${tokenErrText}`);
    }

    const tokenData = await tokenResponse.json() as any;
    const accessToken = tokenData.access_token;
    if (!accessToken) {
      throw new Error("Server succeeded but did not return access_token.");
    }

    // Prepare robust markdown metadata for Test Manager layout
    const markdownDescription = `### Vetted by TestForge Adversarial Review

**Preconditions:**
${testCase.preconditions && testCase.preconditions.length > 0
  ? testCase.preconditions.map((p: string) => `- ${p}`).join("\n")
  : "None configured."}

**Test Sequence Steps:**
${testCase.steps && testCase.steps.length > 0
  ? testCase.steps.map((s: any, idx: number) => `${idx + 1}. **Action:** ${s.action}\n   *Expected:* ${s.expectedResult}`).join("\n\n")
  : "None."}

**Labels:**
${testCase.labels && testCase.labels.length > 0 ? testCase.labels.map((l: string) => `#${l}`).join(", ") : "None."}

---
*Created automatically with TestForge dual-agent QA verification. Status: ${testCase.status || 'vetted'}*`;

    const uipathPayload = {
      name: testCase.title,
      description: markdownDescription,
      priority: testCase.priority ? (testCase.priority.charAt(0).toUpperCase() + testCase.priority.slice(1)) : "Medium",
      steps: testCase.steps ? testCase.steps.map((s: any, idx: number) => ({
        index: idx + 1,
        description: s.action,
        expectedResult: s.expectedResult
      })) : []
    };

    const createUrl = `https://cloud.uipath.com/${org}/${tenant}/testmanager_/api/projects/${projectKey}/testcases`;
    console.log(`Sending payload to Test Manager: ${createUrl}`);

    const apiResponse = await fetch(createUrl, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${accessToken}`,
        "Content-Type": "application/json",
        "Accept": "application/json"
      },
      body: JSON.stringify(uipathPayload),
    });

    if (!apiResponse.ok) {
      const apiErrText = await apiResponse.text();
      throw new Error(`Test Manager API Rejected: ${apiResponse.status} - ${apiErrText}`);
    }

    const resultData = await apiResponse.json() as any;
    const remoteId = resultData.key || resultData.id || `UP-TM-${Math.floor(10000 + Math.random() * 90000)}`;

    res.json({
      success: true,
      remoteId,
      message: "Test case successfully synchronized to UiPath Test Manager!"
    });

  } catch (err) {
    console.error("UiPath Test Manager synchronization error:", err);
    res.status(500).json({
      error: (err as Error).message || "Internal server error connecting to UiPath API.",
      configTip: "Please verify that your client secret & organization parameters are correct and key scopes allow OR.TestManager write access."
    });
  }
});

// Single orchestrated route that client triggers sequentially or as a single endpoint
app.post("/api/generate", async (req: Request, res: Response): Promise<void> => {
  const { requirement, refinementInstruction, previousTestCases } = req.body;

  if (!requirement || requirement.trim() === "") {
    res.status(400).json({ error: "Software requirement is required" });
    return;
  }

  try {
    // Stage 1: Call Builder (round 1)
    let builderRound1Prompt = `Requirement:\n${requirement}`;
    if (refinementInstruction && previousTestCases) {
      builderRound1Prompt += `\n\nRefinement Instruction: ${refinementInstruction}\n\nPrevious active test cases:\n${JSON.stringify(
        previousTestCases
      )}\n\nPlease refine, revise, or generate new test cases conforming to the instruction. Mark any new or updated test cases as status: 'draft'.`;
    }

    const draftTestCases = await generateStructuredJSON<any[]>(
      builderRound1Prompt,
      "You are a senior QA engineer writing test cases for a software requirement. Produce thorough, realistic test cases in the exact JSON schema provided — covering happy path, edge cases, and negative/error cases. Assign realistic priority levels; not everything is critical. Output ONLY valid JSON matching the schema, no prose, no markdown fences.",
      builderRound1ResponseSchema
    );

    // Stage 2: Call Skeptic
    const skepticPrompt = `Requirement:\n${requirement}\n\nProposed drafted test cases:\n${JSON.stringify(
      draftTestCases
    )}`;

    const critiques = await generateStructuredJSON<any[]>(
      skepticPrompt,
      "You are an extremely thorough, skeptical senior QA reviewer. Your ONLY job is to find flaws and gaps in the given test suite relative to the original requirement. Do not be agreeable — assume something was missed and find it. For each issue: if it's a flaw in an EXISTING test case, set targetTestCaseId to that test case's id. If it's something the requirement demands that NO test case covers at all, set targetTestCaseId as an empty string or null and describe what new test case is needed. Be specific — never write a vague critique like 'could be more thorough'; name the exact missing assertion, edge case, or scenario. Output ONLY valid JSON matching the schema, no prose.",
      skepticResponseSchema
    );

    // Stage 3: Call Builder round 2 (Builder Response)
    // If skeptic found nothing, skip straight & finalize drafting cases
    if (!critiques || critiques.length === 0) {
      const finalized = draftTestCases.map((tc) => ({ ...tc, status: "final" }));
      res.json({
        testCases: finalized,
        critiques: [],
        responses: [],
      });
      return;
    }

    // Clean up potentially bad skeptic target IDs
    const validDraftIds = new Set(draftTestCases.map((tc) => tc.id));
    const processedCritiques = critiques.map((c) => {
      // Ensure targetTestCaseId is null/empty if invalid
      if (c.targetTestCaseId && !validDraftIds.has(c.targetTestCaseId)) {
        return { ...c, targetTestCaseId: null };
      }
      return c;
    });

    const builderRound2Prompt = `Requirement:\n${requirement}\n\nDraft test cases:\n${JSON.stringify(
      draftTestCases
    )}\n\nCritique list:\n${JSON.stringify(processedCritiques)}`;

    const responses = await generateStructuredJSON<any[]>(
      builderRound2Prompt,
      "You previously wrote a test suite for this requirement. A reviewer has critiqued it. For EVERY critique listed, you must respond with either 'fixed' (and provide the corrected or newly created test case) or 'rejected' (and explain precisely why the critique doesn't apply — e.g., explicitly out of scope per the requirement). You may not ignore a critique or respond vaguely. If you reject a critique, your explanation must reference the requirement text directly. Output ONLY valid JSON matching the schema, no prose.",
      builderRound2ResponseSchema
    );

    // Merge everything to produce the final test cases
    const mergedTestCases = mergeResponses(draftTestCases, processedCritiques, responses);

    // Mark updated or newly created ones from a refinement pass with a "refinementPassNew" or "new" flag
    let finalPayloadCases = mergedTestCases;
    if (refinementInstruction) {
      const prevIds = new Set((previousTestCases || []).map((p: any) => p.id));
      finalPayloadCases = mergedTestCases.map((tc) => {
        const isNewOrChanged = !prevIds.has(tc.id) || tc.status === "revised";
        if (isNewOrChanged) {
          return { ...tc, isNew: true };
        }
        return tc;
      });
    }

    res.json({
      testCases: finalPayloadCases,
      critiques: processedCritiques,
      responses,
    });
  } catch (err) {
    console.error("Pipeline breakdown error:", err);
    res.status(500).json({
      error: (err as Error).message || "Internal server error during adversarial pipeline run.",
    });
  }
});

// Single step execution routing for user retry-ability
app.post("/api/generate-step", async (req: Request, res: Response): Promise<void> => {
  const { step, requirement, draftTestCases, critiques, refinementInstruction, previousTestCases } = req.body;

  try {
    if (step === "drafting") {
      let builderRound1Prompt = `Requirement:\n${requirement}`;
      if (refinementInstruction && previousTestCases) {
        builderRound1Prompt += `\n\nRefinement Instruction: ${refinementInstruction}\n\nPrevious active test cases:\n${JSON.stringify(
          previousTestCases
        )}\n\nPlease refine, revise, or generate new test cases. Mark any new or updated test cases with status: 'draft'.`;
      }

      const drafts = await generateStructuredJSON<any[]>(
        builderRound1Prompt,
        "You are a senior QA engineer writing test cases. Produce thorough, realistic test cases in the exact JSON schema provided. Output ONLY valid JSON.",
        builderRound1ResponseSchema
      );
      res.json({ draftTestCases: drafts });
      return;
    }

    if (step === "critique") {
      const skepticPrompt = `Requirement:\n${requirement}\n\nProposed drafted test cases:\n${JSON.stringify(
        draftTestCases
      )}`;

      const crits = await generateStructuredJSON<any[]>(
        skepticPrompt,
        "You are an extremely thorough, skeptical senior QA reviewer. Find critical holes and gaps in the drafted test suite relative to the original requirement. Output ONLY valid JSON.",
        skepticResponseSchema
      );
      res.json({ critiques: crits });
      return;
    }

    if (step === "response") {
      const builderRound2Prompt = `Requirement:\n${requirement}\n\nDraft test cases:\n${JSON.stringify(
        draftTestCases
      )}\n\nCritique list:\n${JSON.stringify(critiques)}`;

      const resps = await generateStructuredJSON<any[]>(
        builderRound2Prompt,
        "You written a test suite previously. A reviewer has critiqued it. For EVERY critique listed, respond with either 'fixed' (with corrected/new test case) or 'rejected' explaining why. Output ONLY valid JSON.",
        builderRound2ResponseSchema
      );

      const merged = mergeResponses(draftTestCases, critiques, resps);
      res.json({ responses: resps, testCases: merged });
      return;
    }

    res.status(400).json({ error: `Invalid step type: ${step}` });
  } catch (err) {
    console.error(`Step ${step} failed:`, err);
    res.status(500).json({ error: (err as Error).message });
  }
});

// Setup Vite Dev server or production static serving
async function bootstrapServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req: Request, res: Response) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`TestForge full-stack server listening on http://0.0.0.0:${PORT}`);
  });
}

bootstrapServer().catch((err) => {
  console.error("Server bootstrap failed:", err);
});
